sonar.projectKey=johannesMatevosyan_angular-nest-cicd
sonar.organization=johannesmatevosyan

sonar.sources=apps/frontend/src,apps/backend/src
sonar.tests=apps/frontend/src,apps/backend/src
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/generated/**,**/*.config.ts,**/*.config.cts

sonar.javascript.lcov.reportPaths=coverage/apps/frontend/lcov.info,coverage/apps/backend/lcov.info
